__author__ = "Nico Schlömer"
__author_email__ = "nico.schloemer@gmail.com"
__copyright__ = f"Copyright (c) 2012-2020, {__author__} <{__author_email__}>"
__license__ = "License :: OSI Approved :: MIT License"
__version__ = "0.3.0"
__status__ = "Development Status :: 4 - Beta"
