#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import argparse
import pyfvm


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Convert PyFVM form files into Python modules/C++ headers.'
        )
    parser.add_argument(
        'infile',
        type=str,
        help='input NFL file'
        )
    parser.add_argument(
        'outfile',
        type=str,
        help='output file'
        )
    parser.add_argument(
        '--backend', '-b',
        type=str,
        choices=['scipy', 'nosh'],
        default='scipy'
        )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    pyfvm.compiler.compile(args.infile, args.outfile, args.backend)
